development:
  adapter: postgresql
  encoding: unicode
  database: geoMMO_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: geoMMO_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: ENV['DATABASE_URL'] 
